### ISSUE TITLE
Not work for me _ get error

### ISSUE THREAD

**Issue by i8088** [Xeift/ETH-Batch-Import-Privatekey-Bruteforce#1]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    w3 = web3.Web3(web3.HTTPProvider(os.environ['xxxxxxxxxMyKeyxxxxxxxxx']))
  File "C:\Users\myPC\AppData\Local\Programs\Python\Python38\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'xxxxxxxxxMyKeyxxxxxxxxx'

**Comment by Xeift** [comment]
Change line 8 to `w3 = web3.Web3(web3.HTTPProvider('YOUR_WEB3_PROVIDER_KEY'))` if you run it local
If you run on Replit, make sure you add your web3 provider key to environment variable
